config/routes.rb
Rails.application.routes.draw do 
	get 'home/index' 
	resources :trn_prod_plan_headers 
	resources :trn_prod_plan_masters

	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html 

	get '/trt_masters/:partid', to: 'trt#get_trt_by_part', as: 'trt_masters/'
	get '/material', to: 'material#material_list', as: 'material/' 
	get '/trt_list', to: 'trt#trt_list', as: 'trt_list/' 
end 

app/models/trn_prod_plan_master.rb
class TrnProdPlanMaster < ApplicationRecord
end

app/controllers/trn_prod_plan_masters_controller.rb
class TrnProdPlanMastersController < ApplicationController
  before_action :set_plan_master, only: [:show, :edit, :update, :destroy]

  def index
    @prod_plan_master = TrnProdPlanMaster.new
    @prod_plan_masters_list = TrnProdPlanMaster.select(:id, :trt_code, :sfg_desc, :sfg_code, :day_req_batch, :kanban_size, :frequency_day, :day_req_kanban, :lot_size, :safety_stock, :max_stock, :re_order_point, :action_status).order(:id)
    @mst_material = MstMaterial.select(:id, :mat_code, :mat_desc, :mat_type).where({ mat_uom: "M2" })
  end

  # GET /prod_plan_masters/1
  # GET /prod_plan_masters/1.json
  def show
  end

  # GET /prod_plan_masters/new
  def new 
  end

  # GET /prod_plan_masters/1/edit
  def edit
  end

  # POST /prod_plan_masters
  # POST /prod_plan_masters.json
  def create 
    @prod_plan_master = TrnProdPlanMaster.new(plan_master_params) 
    respond_to do |format|
      if @prod_plan_master.save
        format.html { redirect_to trn_prod_plan_masters_url, success: 'Plan master was successfully created.' }
        format.json { render :index, status: :created, location: @prod_plan_master }
      else
        format.html { render :index }
        format.json { render json: @trn_prod_plan_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prod_plan_masters/1
  # PATCH/PUT /prod_plan_masters/1.json
  def update 
    status = params[:action_status]
    status = status == 'Active'? 'In-Active': 'Active' 
 
    @prod_plan_master.update_column(:action_status, status)

    respond_to do |format| 
        format.html { redirect_to trn_prod_plan_masters_url, info: 'Plan master was successfully updated as ' + status }
        format.json { render :index, status: :ok, location: @prod_plan_master } 
    end
  end

  # DELETE /prod_plan_masters/1
  # DELETE /prod_plan_masters/1.json
  def destroy
    @prod_plan_master.destroy
    respond_to do |format|
      format.html { redirect_to trn_prod_plan_masters_url, success: 'Plan master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan_master
      @prod_plan_master = TrnProdPlanMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_master_params
     # params.fetch(:prod_plan_master, {})
      params.require(:trn_prod_plan_master).permit(:plant, :work_center, :re_order_per, :no_of_hrs, :sfg_code, :sfg_desc, :day_req_batch, :kanban_size, :day_req_kanban, :frequency_day, :lot_size, :safety_stock, :max_stock, :re_order_point, :uom, :action_status, :trt_code)

    end
end

app/helpers/trn_prod_plan_masters_helper.rb
module TrnProdPlanMastersHelper
end

app/views/trn_prod_plan_masters/_form.html.erb
<%= form_with(model: trn_prod_plan_master, id: "form_master", remote: true) do |f| %>
  <div class="form-row"> 
    <%= f.hidden_field :plant,:value => "1080", :required => true, class: 'form-control form-control-sm'%>
    <div class="col-md-2 mb-2"> 
      <label for="work_center">Machine #</label> 
      <%= f.text_field :work_center, :value => "ACAL7201", :required => true, :maxlength => 10, class: 'form-control form-control-sm'%>  
    </div>
    <div class="col-md-2 mb-2">
      <label for="uom">Uom</label>
      <%= f.text_field :uom, :value => "M", :required => true, class: 'form-control form-control-sm'%> 

    </div> 
    <div class="col-md-2 mb-2">
      <label for="re_order_per">Re-order %</label>
      <%= f.number_field :re_order_per, :value => "20", :maxlength => 3, class: 'form-control form-control-sm', id: 'reOrderPer', :onblur=>"calculation()",:required => true, :min => 0%> 
    </div> 
    <div class="col-md-2 mb-2">
     <label for="no_of_hrs">Safety Stock in Hrs</label>
     <%= f.text_field :no_of_hrs, :value => "5",  class: 'form-control form-control-sm', id: 'noOfHrs', :onblur=>"calculation()", :required => true, :min => 0%>      
   </div> 

  </div> 

  <div class="table-responsive">
    <table class="table table-bordered table-hover" id="planMasterTable">
      <thead class="thead-light">
        <tr>
          <th scope="col">TRT </th>
          <th scope="col">SFG Desc. </th>
          <th scope="col">Part #</th>
          <th scope="col" class="text-right">Day Req.(M2) </th>
          <th scope="col" class="text-right">Kanban Size</th>
          <th scope="col" class="text-right">Frequency</th>
          <th scope="col" class="text-right">Day Req. </th>
          <th scope="col" class="text-right">Lot Size</th>
          <th scope="col" class="text-right">Safety Stock</th>
          <th scope="col" class="text-right">Max Stock</th>
          <th scope="col" class="text-right">Re-order Pt</th>
          <th scope="col">Status</th> 
        </tr>
      </thead>
      <tbody>
        <% plan_masters_list.each do |p| %>
        <tr>

          <td class="align-middle"><%= p.trt_code %></td> 
          <td class="align-middle"><%= p.sfg_desc %></td> 
          <td class="align-middle"><%= p.sfg_code %></td> 
          <td class="text-right align-middle"><%= p.day_req_batch %></td> 
          <td class="text-right align-middle"><%= p.kanban_size %></td> 
          <td class="text-right align-middle"><%= p.frequency_day %></td> 
          <td class="text-right align-middle"><%= p.day_req_kanban %></td> 
          <td class="text-right align-middle"><%= p.lot_size %></td> 
          <td class="text-right align-middle"><%= p.safety_stock %></td> 
          <td class="text-right align-middle"><%= p.max_stock %></td> 
          <td class="text-right align-middle"><%= p.re_order_point %></td> 
          <td class="align-middle">  
<%= link_to p.action_status, trn_prod_plan_master_path(:id => p.id, :action_status => p.action_status), method: :put,remote: true %>   
<span class="float-right">
        <%= link_to  p, method: :delete, remote: true, data: { confirm: "Are you sure?" } do %>
          <i class="far fa-trash-alt" role="button"> </i>
        <% end %>
      </span>
    </td> 
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
  <%= button_tag 'Add', onclick: "addRowMaster()", type: 'button', :class => "btn btn-primary"%> 
  <%= button_tag 'Clear', type: 'reset', :class => "btn btn-secondary"%> 
  <%= button_tag 'Submit', id:"btnSubmit", :onclick => "return validation()", type: 'submit', :class => "btn btn-primary", data: { disable_with: "Submitting..."}
%>   

  <%= button_tag 'Cancel', type: 'button', :class => "btn btn-secondary removeRow"%>   

  <% if trn_prod_plan_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trn_prod_plan_master.errors.count, "error") %> prohibited this trn_prod_plan_master from being saved:</h2>

      <ul>
        <% trn_prod_plan_master.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
<% end %>   
<script type="text/javascript">  
  
  function validation() {  
    var dayReqBatch = document.getElementById('dayReqBatch');
    var kanbanSize = document.getElementById('kanbanSize');
    var frequencyDay = document.getElementById('frequencyDay'); 

    if (dayReqBatch == null || kanbanSize == null || frequencyDay == null) {
      return false;
    }
    calculation();
    return true;

  }

  function addRowMaster() {
    if (document.getElementById('newrow') !== null) {
      return false;
    }
    trtAutocomplete();
    var tr = document.getElementById('newrow');
    var empTab = document.getElementById('planMasterTable');
    var rowCnt = empTab.rows.length; // GET TABLE ROW COUNT.
    var tr = empTab.insertRow(rowCnt);
    tr.id = "newrow"
    var tdEle = document.createElement('td');
    var eleSelect = document.createElement('SELECT');
    var option = document.createElement("option");
    setAttributes(eleSelect, {
      "id": "action_status",
      "class": "form-control form-control-sm",
      "style": "width:90px",
      "name": "trn_prod_plan_master[action_status]"
    });
    option.text = "Active";
    eleSelect.add(option);
    option = document.createElement("option");
    option.text = "In-active";
    eleSelect.add(option);
    td = tr.insertCell(tdEle);
    td.appendChild(eleSelect);
    var ele = document.createElement('input');
    ele.readOnly = true;
    setAttributes(ele, {
      "id": "reOrderPoint",
      "type": "number",
      "value": "0",
      "class": "form-control form-control-sm text-right",
      "name": "trn_prod_plan_master[re_order_point]"
    });
    td = tr.insertCell(tdEle);
    td.appendChild(ele);
    ele = document.createElement('input');
    ele.readOnly = true;
    setAttributes(ele, {
      "id": "maxStock",
      "type": "number",
      "value": "0",
      "class": "form-control form-control-sm text-right",
      "name": "trn_prod_plan_master[max_stock]"
    });
    td = tr.insertCell(tdEle);
    td.appendChild(ele);
    ele = document.createElement('input');
    ele.readOnly = true;
    setAttributes(ele, {
      "id": "safetyStock",
      "type": "number",
      "value": "0",
      "class": "form-control form-control-sm text-right",
      "name": "trn_prod_plan_master[safety_stock]"
    });
    td = tr.insertCell(tdEle);
    td.appendChild(ele);
    ele = document.createElement('input');
    ele.readOnly = true;
    setAttributes(ele, {
      "id": "lotSize",
      "type": "number",
      "value": "0",
      "class": "form-control form-control-sm text-right",
      "name": "trn_prod_plan_master[lot_size]"
    });
    td = tr.insertCell(tdEle);
    td.appendChild(ele);
    ele = document.createElement('input');
    ele.readOnly = true;
    setAttributes(ele, {
      "id": "dayReqKanban",
      "type": "number",
      "value": "0",
      "class": "form-control form-control-sm text-right",
      "name": "trn_prod_plan_master[day_req_kanban]"
    });
    td = tr.insertCell(tdEle);
    td.appendChild(ele);
    ele = document.createElement('input');
    setAttributes(ele, {
      "id": "frequencyDay",
      "type": "number",
      "value": "",
      "class": "form-control form-control-sm text-right",
      "name": "trn_prod_plan_master[frequency_day]",
      "onblur": "return calculation()",
      "required": "true",
      "min": "0"
    });
    td = tr.insertCell(tdEle);
    td.appendChild(ele);
    ele = document.createElement('input');
    setAttributes(ele, {
      "id": "kanbanSize",
      "type": "number",
      "value": "",
      "class": "form-control form-control-sm text-right",
      "name": "trn_prod_plan_master[kanban_size]",
      "onblur": "return calculation()",
      "required": "true",
      "min": "0"
    });
    td = tr.insertCell(tdEle);
    td.appendChild(ele);
    ele = document.createElement('input');
    setAttributes(ele, {
      "id": "dayReqBatch",
      "type": "number",
      "value": "",
      "class": "form-control form-control-sm text-right",
      "name": "trn_prod_plan_master[day_req_batch]",
      "onblur": "return calculation()",
      "required": "true",
      "min": "0"
    });
    td = tr.insertCell(tdEle);
    td.appendChild(ele);
    ele = document.createElement('input'); 
    setAttributes(ele, {
      "id": "sfgCode",
      "value": "",
      "class": "form-control form-control-sm readonly",
      "name": "trn_prod_plan_master[sfg_code]",
      "style": "width:150px",
      "autocomplete":"off",
      "required": "true",
      "oninvalid":"this.setCustomValidity('Fill this by selecting valid TRT number')" 
    });
    td = tr.insertCell(tdEle);
    td.appendChild(ele);
    ele = document.createElement('input'); 
    setAttributes(ele, {
      "id": "sfgDesc",
      "value": "",
      "class": "form-control form-control-sm readonly",
      "name": "trn_prod_plan_master[sfg_desc]",
      "style": "width:210px",
      "autocomplete":"off" 
    });
    td = tr.insertCell(tdEle);
    td.appendChild(ele);
    ele = document.createElement('input');
    setAttributes(ele, {
      "id": "trt_code",
      "class": "auto-form-control form-control form-control-sm",
      "name": "trn_prod_plan_master[trt_code]",
      "required": "true"
    });
    td = tr.insertCell(tdEle);
    td.appendChild(ele);
  }

  function calculation() {
    var dayReqBatch = document.getElementById('dayReqBatch');
    var kanbanSize = document.getElementById('kanbanSize');
    var frequencyDay = document.getElementById('frequencyDay');
    var noOfHrs = document.getElementById('noOfHrs');
    var reOrderPer = document.getElementById('reOrderPer');
    if (dayReqBatch == null || kanbanSize == null || frequencyDay == null || noOfHrs == null || reOrderPer == null) {
      return false;
    }
    var dayReqBatchValue = parseInt(dayReqBatch.value);
    var kanbanSizeValue = parseInt(kanbanSize.value);
    var frequencyDayValue = parseInt(frequencyDay.value);
    var noOfHrsValue = parseInt(noOfHrs.value);
    var reOrderPerValue = parseInt(reOrderPer.value);
    if (isNaN(dayReqBatchValue) || dayReqBatchValue < 0 || isNaN(kanbanSizeValue) || kanbanSizeValue < 0 || isNaN(frequencyDayValue) || frequencyDayValue < 0 ||
      isNaN(noOfHrsValue) || noOfHrsValue < 0 || isNaN(reOrderPerValue) || reOrderPerValue < 0) {
      return false;
    }
    var dayReqKanban = calDayReqKanban(dayReqBatchValue, kanbanSizeValue);
    document.getElementById('dayReqKanban').value = dayReqKanban;
    if (dayReqKanban == null || dayReqKanban < 0) {
      return false;
    }
    var lotSize = calLotSize(dayReqKanban, frequencyDayValue);
    document.getElementById('lotSize').value = lotSize;
    var safetyStock = calSafetyStock(dayReqKanban, noOfHrsValue);
    document.getElementById('safetyStock').value = safetyStock;
    if (lotSize == null || lotSize < 0) {
      return false;
    }
    document.getElementById('maxStock').value = calMaxStock(lotSize, safetyStock);
    document.getElementById('reOrderPoint').value = calReOrderPoint(safetyStock, reOrderPerValue, lotSize);
  }

  function calDayReqKanban(dayReqBatch, kanbanSize) {
    dayReqKanban = Math.round(dayReqBatch / kanbanSize);
    console.log(dayReqKanban);
    return dayReqKanban > 0 ? dayReqKanban : 0;
  }

  function calLotSize(dayReqKanban, frequencyDay) {
    kanbanSize = Math.round(dayReqKanban / frequencyDay);
    return kanbanSize > 0 ? kanbanSize : 0;
  }

  function calSafetyStock(dayReqKanban, noOfHrs) {
    frequencyDay = Math.round(parseFloat(dayReqKanban / 24) * noOfHrs);
    return frequencyDay > 0 ? frequencyDay : 0;
  }

  function calMaxStock(lotSize, safetyStock) {
    noOfHrs = Math.round(lotSize + safetyStock);
    return noOfHrs > 0 ? noOfHrs : 0;
  }

  function calReOrderPoint(safetyStock, reOrderPer, lotSize) {
    reOrderPer = Math.round(safetyStock * (parseFloat(parseFloat(reOrderPer / 100) * lotSize)));
    return reOrderPer > 0 ? reOrderPer : 0;
}


</script>

app/views/trn_prod_plan_masters/edit.html.erb
<h1>Editing Trn Prod Plan Master</h1>

<%= render 'form', trn_prod_plan_master: @trn_prod_plan_master %>

<%= link_to 'Show', @trn_prod_plan_master %> |
<%= link_to 'Back', trn_prod_plan_masters_path %>

app/views/trn_prod_plan_masters/index.html.erb
<div class="container-fluid">
<h5>Production Plan</h5>
  <%= render 'form', trn_prod_plan_master: @prod_plan_master, plan_masters_list: @prod_plan_masters_list %>
</div>

app/views/trn_prod_plan_masters/new.html.erb
<h1>New Trn Prod Plan Master</h1>

<%= render 'form', trn_prod_plan_master: @trn_prod_plan_master %>

<%= link_to 'Back', trn_prod_plan_masters_path %>

app/views/trn_prod_plan_masters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_trn_prod_plan_master_path(@trn_prod_plan_master) %> |
<%= link_to 'Back', trn_prod_plan_masters_path %>